# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: TestRail CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      EMAIL: ${{secrets.SD_EMAIL}}
      PASS: ${{secrets.SD_PASSWORD}}
      BASE_URL: ${{secrets.SD_BASE_URL}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        browser: firefox
        version: latest
    - name: Run tests
      run: mvn clean test -Demail=$EMAIL -Dpassword=$PASS -DbaseURL=$BASE_URL
    - name: Run cross-browser tests
      run: mvn test -Demail=$EMAIL -Dpassword=$PASS -DbaseURL=$BASE_URL -DsuiteXmlFile='src/test/resources/CrossBrowserTest.xml'

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history